# name: Push to main
# run-name: Deploy on push to main

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'apps/app/**'
#       - 'apps/app/*'
#       - 'apps/landing/**'
#       - 'apps/landing/*'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Install Node.js v18
#         uses: actions/setup-node@v2
#         with:
#           node-version: '18.x'
#       - name: Install pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: 7
#       - name: Install TurboRepo CLI
#         run: pnpm install turbo --global
#       - name: Check for workspace changes
#         # run: turborepo diff  - chatGPT, never worked.
#         id: check_changes
#       - name: Deploy app changes
#         if: ${{ contains(env.diff, 'apps/app') }}
#         run: |
#           curl https://api.vercel.com/v1/integrations/deploy/prj_gMacbOOPHFgcG68cSURKttHFBCMj/IA81oGLHua
#       - name: Deploy landing changes
#         if: ${{ contains(env.diff, 'apps/landing') }}
#         run: |
#           curl https://api.vercel.com/v1/integrations/deploy/prj_kSMzWzQkxLTCqV7DI67hVgXuPYO2/vEJckOuzyq
