export default function Head() {
  return (
    <>
      <title>Home</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      {/* <link rel='icon' type='image/png' sizes='16x16' href='/images/old-favicon.ico' /> */}
      {/* <link rel='icon' type='image/png' sizes='16x16' href='/logo/favicon2.ico' /> */}
      {/* <link rel='icon' type='image/png' sizes='16x16' href='/logo/favicon.ico' /> */}
      <link rel='icon' type='image/png' sizes='16x16' href='/logo/logo-d-trans.png' />
      {/* <link rel="icon" type="image/png" sizes="16x16" href="../favicon.ico" /> */}
      {/* <link rel="icon" href="../../public/favicon.ico" /> */}
    </>
  );
}
