import '../styles/globals.scss';
// import "ui/styles.css"; // might need this

// Figure this out. New way to do head I think - instead of file
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='bg-pink-300'>
      <body>{children}</body>
    </html>
  );
}
