name: Deploy on Changes to Next.js Apps
on:
  # pull_request:
  #   types: [opened, reopened]
  push:
    branches:
      - main
    paths:
      - 'apps/app/**'
      - 'apps/app/*'
      - 'apps/landing/**'
      - 'apps/landing/*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary for comparing changes to past commits

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 9

      # - name: Install TurboRepo CLI
      #   run: pnpm i turbo --global

      # - name: Verify pnpm and turbo versions
      #   run: |
      #     pnpm --version
      #     turbo --version

      - name: app changed in last commit?
        id: changedActionApp
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: app
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead in the form of origin/<branchName>)

      - name: Validate Action Output
        if: steps.changedActionApp.outputs.changed == 'true' # Check output if it changed or not (returns a boolean)
        run: |
          echo "Detected changes in app: App. Deploying to Vercel"
          curl https://api.vercel.com/v1/integrations/deploy/prj_pIjgANGuuYB6DTezAaPiHYcBJerb/5PICX8gHCa

      - name: landing changed in last commit?
        id: changedActionLanding
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: landing
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead in the form of origin/<branchName>)

      - name: Validate Action Output
        if: steps.changedActionLanding.outputs.changed == 'true' # Check output if it changed or not (returns a boolean)
        run: |
          echo "Detected changes in app: Landing. Deploying to Vercel"
          curl https://api.vercel.com/v1/integrations/deploy/prj_ZuS0TyO3wfg89YoINFUPuyqyTvl9/tMNpP6nB0Q
